apiVersion: v1
kind: Service
metadata:
  namespace: mysystem
  name: mysystem-db-node5-service
  labels:
    name: database
    node: node5
    system: mysystem
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database
    node: node5
    system: mysystem