apiVersion: v1
kind: Pod
metadata:
  name: application-db-node3
  labels:
    name: database
    node: node3
    system: application
spec:
  containers:
    -
      name: application-db-node3
      image: paunin/postgresql-cluster-pgsql
      env:
        -
          name: "REPLICATION_PRIMARY_HOST"
          value: "application-db-node1-service"
        -
          name: "NODE_ID"
          value: "3"
        -
          name: "NODE_NAME"
          value: "node3"
        -
          name: "CLUSTER_NODE_NETWORK_NAME"
          value: "application-db-node3-service"

        # Cluster configs
        - name: "CLUSTER_NAME"
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: app.db.cluster.name
        - name: "REPLICATION_DB"
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: app.db.cluster.replication.db
        - name: "REPLICATION_USER"
          valueFrom:
            secretKeyRef:
              name: application-secret
              key: app.db.cluster.replication.user
        - name: "REPLICATION_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: application-secret
              key: app.db.cluster.replication.password
      ports:
        -
          containerPort: 5432
      volumeMounts:
        - mountPath:  /var/lib/postgresql/data
          name: pg-data-volume
  volumes:
    - name: pg-data-volume
      persistentVolumeClaim:
        claimName: application-db-node3-claim
