apiVersion: v1
kind: Pod
metadata:
  name: database-node4
  labels:
    name: database
    node: node4
spec:
  containers:
    -
      name: database-node4
      image: paunin/postgresql-cluster-pgsql
      env:
        -
          name: "REPLICATION_PRIMARY_HOST"
          value: "database-node1-service"
        -
          name: "NODE_ID"
          value: "4"
        -
          name: "NODE_NAME"
          value: "node4"
        -
          name: "CLUSTER_NODE_NETWORK_NAME"
          value: "database-node4-service"
      ports:
        -
          containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database-node4-service
  labels:
    name: database
    node: node4
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database
    node: node4