apiVersion: v1
kind: Pod
metadata:
  name: database-node3
  labels:
    name: database
    node: node3
spec:
  containers:
    -
      name: database-node3
      image: paunin/postgresql-cluster-pgsql
      env:
        -
          name: "REPLICATION_PRIMARY_HOST"
          value: "database-node2-service"
        -
          name: "NODE_ID"
          value: "3"
        -
          name: "NODE_NAME"
          value: "node3"
        -
          name: "CLUSTER_NODE_NETWORK_NAME"
          value: "database-node3-service"
      ports:
        -
          containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database-node3-service
  labels:
    name: database
    node: node3
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database
    node: node3