apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    node: node1
    system: application-db
    namespace: application-master
    type: amazonEBS
  name: pv-application-db-node1
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-xxxxxxx
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain