apiVersion: v1
kind: Secret
metadata:
  name: application-secret
type: Opaque
data:
  app.db.user: YXBwbGljYXRpb25fdXNlcg== #application_user
  app.db.password: YXBwbGljYXRpb25fcGFzcw== #application_pass
  app.db.cluster.replication.user: cmVwbGljYV91c2Vy #replica_user
  app.db.cluster.replication.password: cmVwbGljYV9wYXNz #replica_pass
  app.db.pool.users: YXBwbGljYXRpb25fdXNlcjphcHBsaWNhdGlvbl9wYXNz #application_user:application_pass
  app.db.pool.pcp.user: cGNwX3VzZXI= #pcp_user
  app.db.pool.pcp.password: cGNwX3Bhc3M= #pcp_pass